name = "ImageView"
uuid = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
author = ["Tim Holy <tim.holy@gmail.com"]
version = "0.12.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
GtkObservables = "8710efd8-4ad6-11eb-33ea-2d5ceb25a41c"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
MultiChannelColors = "d4071afc-4203-49ee-90bc-13ebeb18d604"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RoundingIntegers = "d5f540fe-1c90-5db3-b776-2e2f362d9394"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AxisArrays = "0.3, 0.4"
Cairo = "0.6, 0.7, 0.8, 1"
Compat = "3, 4"
Graphics = "0.2, 0.3, 0.4, 1"
Gtk4 = "0.5, 0.6"
GtkObservables = "2"
ImageBase = "0.1"
ImageCore = "0.9, 0.10"
ImageMetadata = "0.9"
MultiChannelColors = "0.1.1"
PrecompileTools = "1"
RoundingIntegers = "0.2, 1"
StatsBase = "0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34"
julia = "1.6"

[extras]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Observables = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["ImageCore", "ImageIO", "IntervalSets", "OffsetArrays", "Observables", "Test", "TestImages"]
