name = "ImageView"
uuid = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
author = ["Tim Holy <tim.holy@gmail.com"]
version = "0.10.15"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkReactive = "27996c0f-39cd-5cc1-a27a-05f136f946b6"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
RoundingIntegers = "d5f540fe-1c90-5db3-b776-2e2f362d9394"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AxisArrays = "0.3, 0.4"
Cairo = "0.6, 0.7, 0.8, 1"
Graphics = "0.2, 0.3, 0.4, 1"
Gtk = "0.16, 0.17, 0.18, 1"
GtkReactive = "0.5.1, 0.6, 0.7, 1"
ImageBase = "0.1"
ImageCore = "0.9"
ImageMetadata = "0.9"
RoundingIntegers = "0.2, 1"
StatsBase = "0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
julia = "1"

[extras]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["ImageCore", "ImageMagick", "IntervalSets", "OffsetArrays", "QuartzImageIO", "Reactive", "Test", "TestImages"]
